loader/urls.py
from django.urls import path

from . import views






urlpatterns = [
    path('', views.HomePageView.as_view(), name='index'),
    path('history/', views.HistoryPageView.as_view(), name='history'),
    path('download/', views.DownloadPageView.as_view(), name='download'),
    path('download/confirm', views.Confirm.as_view(), name='confirm'),
    path('email/', views.email_page, name='email')
]

videoloader/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('loader.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

loader/models.py
from django.db import models
from django.urls import reverse


class Link(models.Model):
     link = models.URLField(max_length=300, default='')
     email = models.CharField(max_length=50, default='')


     def __str__(self):
         return '%s %s' % (self.link, self.email)


     def get_absolute_url(self):
         return reverse('confirm')

loader/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic import TemplateView, ListView
from .models import Link
from django.views.generic.edit import CreateView
# from django.core.mail import send_mail
from .tasks import email
# from celery.result import AsyncResult


class HomePageView(TemplateView):
    template_name = "loader/index.html"


class HistoryPageView(ListView):
    model = Link
    template_name = "loader/history.html"


class DownloadPageView(CreateView):
    model = Link
    template_name = 'loader/download.html'
    fields = '__all__'


class Confirm(ListView):
    model = Link
    template_name = "loader/confirm.html"

def email_page(request):
    email.delay()
    return render(request, 'loader/email.html')

loader/templates/loader/confirm.html
{% extends 'base.html' %}

{% block content %}

<h1> <a target="_blank" href="{{ link_list.last.link }}"> Watch the video </a> </h1>

<form action='{% url 'email' %}'>{% csrf_token %}
<input type="submit" value="Sent an email to {{ link_list.last.email }}" />
</form>

<h3>Do you want to download an mp3 file?</h3>

<form action='{% url 'index' %}'>{% csrf_token %}
<input type="submit" value="Yes" />
</form>

<form action='{% url 'index' %}'>
<input type="submit" value="No" />
</form>

<ul>
{% for item in link %}
<li><a target='_blank' href="{{ item }}"> {{ item }} </a></li>
{% endfor %}
</ul>






{% endblock %}

loader/templates/loader/download.html
{% extends 'base.html' %}
{% block content %}
<h2>Put the link: </h2>
<form action="" method="post">{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="Submit" />



</form>
{% endblock %}

loader/templates/loader/email.html
{% extends 'base.html' %}
{% block content %}
<h1> You will receive in a minute:) </h1>
{% endblock %}

loader/templates/loader/history.html
{% extends 'base.html' %}


{% block content %}


<ul>
{% for item in post_list %}
<li><a target='_blank' href="{{ item }}"> {{ item }} </a></li>
{% endfor %}
</ul>



<ul>
{% for item in link_list %}
<li><a target='_blank' href="{{ item.link }}"> {{ item.link }} </a></li>
{% endfor %}
</ul>



<a href="/media/download.mp3" download="download">Download Last Audio File</a>





{% endblock %}

loader/templates/loader/index.html
{% extends 'base.html' %}
{% block content %}

<h4>Click Download music and put the link.</h4>
<h4>All inputted links are saved in History.</h4>
<h4>If you want to delete links in history, go to /admin/ and login (name: admin, password: admin).</h4>

{% endblock %}